name: CI

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: Install correct version of mingw
      run: |
        choco uninstall mingw --force
        choco uninstall strawberryperl --force

    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW32
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.5.3
      with:
        version: ${{ env.QT_VERSION }}
        arch:    ${{ env.MINGW_VERSION }}
        extra:   --external 7z

    - uses: actions/checkout@v1

    - name: Qmake and make
      working-directory: d:/a/qt-github-build-32/qt-github-build-32
      run: | 
        qmake.exe qt-github-build-32.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
        mingw32-make.exe qmake_all
        
    - name: Make mingw32
      working-directory: d:/a/qt-github-build-32/qt-github-build-32
      run: |
        mingw32-make.exe -j8
